### ISSUE TITLE
分类和归档里面为啥没有下一页或加载更多？

### ISSUE THREAD

**Issue by zekunyan** [raytaylorlin/hexo-theme-raytaylorism#9]
如图：
![image](http://ww1.sinaimg.cn/large/0060lm7Tgw1f23exyjx8ij31ak0uiq8z.jpg)

**Comment by raytaylorlin** [comment]
分类和归档页面是全部都显示出来的，没有分页

**Comment by raytaylorlin** [comment]
在你的yourblog/_config.yml配置文件的#pagination的位置添加下面配置（禁用归档、标签、目录页面的分页功能）

```
archive_generator:
  per_page: 0
tag_generator:
  per_page: 0
category_generator:
  per_page: 0
```
